# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd02cae11f74366e87a2c4a55d55e6e784d715357e59c84044c4589bc08830539a12737eadc9f11365122e7a28540511efaaabdd0f62f2782a01b908803c651c

test:
  secret_key_base: 86d931caab535e12b52c531286e58377c11b9ee7dabe0ea47588453913f283dbd55a1f24c2d6b6a5ec713bd7dc273e25ceb39a938e49b3faa82114deab7de4e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
